### ISSUE TITLE
composer require Error

### ISSUE THREAD

**Issue by johnhydemtm365** [cundd/rest#57]
Hi, have you added support for this breaking change?
https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/9.0/Breaking-83302-ComposerRestrictsInstallationOfTypo3cms.html

As when I then run  'composer require cundd/rest'  it fails in a big way, see file:

[Error.txt](https://github.com/cundd/rest/files/2968463/Error.txt)

Basically I am building a docker image installing composer and then trying to install the extension, but having no joy...

Thanks
J

**Comment by cundd** [comment]
Hi

The extensions `composer.json` doesn’t mention TYPO3 at all. I want the extension to be as decoupled from TYPO3 as possible (which e.g. lets me use the Routing in another project). 

So I think the problem comes from somewhere else. 

What I am not sure is, if the Dockerfile has any impact when required inside an docket image - but that would be very strange

**Comment by johnhydemtm365** [comment]
Hi, so yes as it turns out its an issue with composer.

Appreciate the fast response.

J
