### ISSUE TITLE
how to get content of languages ?

### ISSUE THREAD

**Issue by issibi** [cundd/rest#64]
in manual it says:
Specify the GET-parameter L with the language UID

I could not find out how this works.

Example:
I have a site Setup with /de (L=0) and /en (L=1)

In TS i have:
plugin.tx_rest.settings {
  languages {
      de = 0
      en = 1
    }
}

How to get the content for the german language ?
Something like this does not work
domain.com/rest/VirtualObject-Content/0
domain.com/rest/VirtualObject-Content/L/0

**Comment by cundd** [comment]
TLDR: This is not possible with `VirtualObject`s.

`VirtualObject`s are a special construct. They are more like a raw database query, rather than a regular TYPO3 Extbase model. The problem is, that the VO-system has no knowledge of the language of a record.

I'm currently looking for someone to sponsor the implementation of a better system to fetch pages and content (https://rest.corn.rest/_Initiatives/Headless/).

**Comment by issibi** [comment]
I see, thnx for info. Since the systemLanguageUid is in the JSON we will use this info for now.
Thnx for this great extension.
